version: "3.8"
services:
  nginx-proxy-manager:
    image: docker.io/jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data/nginx:/data
      - ./data/letsencrypt:/etc/letsencrypt
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: 
    volumes:
      - ./data/cloudflared:/etc/cloudflared
  dash:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped
    privileged: true
    ports:
      - 3004:3001
    volumes:
      - /:/mnt/host:ro
  stremio-postgres:
    image: postgres:16.3-alpine3.20
    container_name: stremio-postgres
    restart: unless-stopped
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: stremio
      POSTGRES_PASSWORD: stremio
      POSTGRES_DB: zilean
    volumes:
      - ./data/stremio-postgres:/var/lib/postgresql/data/pgdata
      - ./opt/stacks/stremio/initdb:/docker-entrypoint-initdb.d
  stremio-redis:
    image: redis:latest
    container_name: stremio-redis
    restart: unless-stopped
    volumes:
      - ./data/stremio-redis:/data
  aiometadata_redis:
    image: redis:latest
    container_name: aiometadata_redis
    restart: unless-stopped
    volumes:
      - ./data/aiometadata/cache:/data
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    ports:
      - 3005:3000
    environment:
      BASE_URL: 
      SECRET_KEY: 
      DATABASE_URI: postgresql://stremio:stremio@stremio-postgres:5432/zilean
      BUILTIN_GET_TORRENT_LAZILY: "false"
      BUILTIN_JACKETT_URL: 
      BUILTIN_JACKETT_API_KEY: 
      REGEX_FILTER_ACCESS: all
    depends_on:
      - stremio-postgres
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris
      AUTO_UPDATE: "true"
    volumes:
      - ./data/jackett:/config
      - ./data/jackett/downloads:/downloads
    ports:
      - 9118:9117
  aiometadata:
    image: ghcr.io/cedya77/aiometadata:latest
    container_name: aiometadata
    restart: unless-stopped
    ports:
      - 3233:3232
    environment:
      PORT: "3232"
      HOST_NAME: 
      REDIS_URL: redis://aiometadata_redis:6379
      META_TTL: "604800"
      CATALOG_TTL: "86400"
      CATALOG_LIST_ITEMS_SIZE: "20"
      LOG_LEVEL: debug
      ADMIN_KEY: TEST
      DATABASE_URI: postgresql://stremio:stremio@stremio-postgres:5432/zilean
    volumes:
      - ./data/aiometadata:/app/addon/data
    depends_on:
      - stremio-postgres
      - aiometadata_redis
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./data/kuma:/app/data
    ports:
      - 3002:3001
  stream-fusion:
    image: ghcr.io/beluchon/stream-fusion:latest
    container_name: stream-fusion
    restart: unless-stopped
    ports:
      - 8082:8080
    environment:
      SECRET_API_KEY: 
      TMDB_API_KEY: 
      YGG_PASSKEY: 
      SHAREWOOD_PASSKEY: ""
      DATABASE_URI: postgresql://stremio:stremio@stremio-postgres:5432/zilean
      PG_HOST: stremio-postgres
      PG_USER: stremio
      PG_PASS: stremio
      REDIS_HOST: stremio-redis
      USE_HTTPS: "True"
      TZ: Europe/Paris
      ZILEAN_ENABLED: "false"
      DB_CONNECTION_RETRIES: "15"
      DB_RETRY_DELAY: "5"
    volumes:
      - ./data/stream-fusion:/app/config
    depends_on:
      - stremio-postgres
      - stremio-redis
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: "10000"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_LABEL_ENABLE: "false"
      TZ: Europe/Paris
networks: {}
